---
name: Auth Service

on:
  push:
    branches:
      - main
    paths:
      - services/auth/**
  pull_request:
    branches:
      - main
    paths:
      - services/auth/**

jobs:
  test:
    uses: ./.github/workflows/node-test.yml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      service: auth
  build-and-publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/container-build.yml
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    with:
      service: auth
...
