---
name: GKE Deployment

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      gke_project:
        required: true
      gke_cluster:
        required: true
      gke_region:
        required: true
      workload_identity_provider:
        required: true
      service_account:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/${{ inputs.service }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        working-directory: kubernetes-manifests/services/${{ inputs.service }}/overlays/${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.workload_identity_provider }}
        service_account: ${{ secrets.service_account }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.gke_cluster }}
        location: ${{ secrets.gke_region }}
        project_id: ${{ secrets.gke_project }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=match,pattern=${{ inputs.service }}-v(.*),group=1,event=tag
          type=sha,format=long,event=branch
    
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
  
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image ${{ steps.meta.outputs.tags }}
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/${{ inputs.service }} -n ${{ inputs.environment }}
        kubectl get services -o wide -n ${{ inputs.environment }}
...
