---
name: Go

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

defaults:
  run:
    working-directory: services/${{ inputs.service }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Go
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o app ./...
      - name: Test
        run: go test -v ./...
...
