---
name: Node.js Workflow

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v3
        with:
          all-files: true
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js'
          annotations: true
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ inputs.service }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: services/${{ inputs.service }}
          push: false
...
