---
name: User Service

on:
  push:
    branches:
      - main
    paths:
      - services/user/**
  pull_request:
    branches:
      - main
    paths:
      - services/user/**

jobs:
  test:
    uses: ./.github/workflows/go-test.yml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      service: user
  build-and-publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/container-build.yml
    if: ${{ github.event_name == 'pull_request' }}
    with:
      service: user
...
