---
name: User Service

on:
  pull_request:
    branches:
      - main
    paths:
      - services/user/**

jobs:
  test:
    uses: ./.github/workflows/go-workflows/go-test.yml
    with:
      service: user
...
