---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stg

resources:
- ../../base
- managed-cert.yaml

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
...
